In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/ethanalter/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

#### numpy allows you to create multi-dimensional arrays 

In [3]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
var = np.arange(20).reshape(5,4)

In [5]:
var

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

this is a "table" 5 rows and 4 columns 

In [7]:
#axis 0 operates on the columns
var.sum(axis=0)

array([40, 45, 50, 55])

In [8]:
#axis 1 operates on the rows 
var.sum(axis=1)

array([ 6, 22, 38, 54, 70])

numpy is a low-level library - not really meant for end consumer use
* sort of like the bottom layer for the data software stack

### Pandas uses dataframes and allows for more interactivity with outside data

Pandas is what you use to get work from Excel into Python and work with it programmatically

In [10]:
import pandas as pd

In [11]:
# SHIFT COMMAND C to copy a file path 
url = r"/Users/ethanalter/Dropbox (Personal)/GA-4K-DataScience/gazelle-4K/data/master.csv"

**r = raw** - basically telling Python to ignore special characters
The r in front of the string is necessary only on Windows to sort of "escape" the backslashes in Windows filepaths. On a Mac, we good because Macs use backslashes in filepaths 

In [12]:
url

'/Users/ethanalter/Dropbox (Personal)/GA-4K-DataScience/gazelle-4K/data/master.csv'

In [14]:
df = pd.read_csv(url)

In [15]:
#displaying more rows
df.head(30)

id  visit_date  visitors day_of_week  holiday  \
0   air_ba937bf13d40fb24  2016-01-13        25   Wednesday        0   
1   air_ba937bf13d40fb24  2016-01-14        32    Thursday        0   
2   air_ba937bf13d40fb24  2016-01-15        29      Friday        0   
3   air_ba937bf13d40fb24  2016-01-16        22    Saturday        0   
4   air_ba937bf13d40fb24  2016-01-18         6      Monday        0   
5   air_ba937bf13d40fb24  2016-01-19         9     Tuesday        0   
6   air_ba937bf13d40fb24  2016-01-20        31   Wednesday        0   
7   air_ba937bf13d40fb24  2016-01-21        21    Thursday        0   
8   air_ba937bf13d40fb24  2016-01-22        18      Friday        0   
9   air_ba937bf13d40fb24  2016-01-23        26    Saturday        0   
10  air_ba937bf13d40fb24  2016-01-25        21      Monday        0   
11  air_ba937bf13d40fb24  2016-01-26        11     Tuesday        0   
12  air_ba937bf13d40fb24  2016-01-27        24   Wednesday        0   
13  air_ba937bf13d40fb24  2016-01-28        21    Thursday        0   
14  air_ba937bf13d40fb24  2016-01-29        26      Friday        0   
15  air_ba937bf13d40fb24  2016-01-30         6    Saturday        0   
16  air_ba937bf13d40fb24  2016-02-03        18   Wednesday        0   
17  air_ba937bf13d40fb24  2016-02-04        12    Thursday        0   
18  air_ba937bf13d40fb24  2016-02-05        45      Friday        0   
19  air_ba937bf13d40fb24  2016-02-06        15    Saturday        0   
20  air_ba937bf13d40fb24  2016-02-08        19      Monday        0   
21  air_ba937bf13d40fb24  2016-02-09        15     Tuesday        0   
22  air_ba937bf13d40fb24  2016-02-10        32   Wednesday        0   
23  air_ba937bf13d40fb24  2016-02-11         3    Thursday        1   
24  air_ba937bf13d40fb24  2016-02-12        26      Friday        0   
25  air_ba937bf13d40fb24  2016-02-13         8    Saturday        0   
26  air_ba937bf13d40fb24  2016-02-15        14      Monday        0   
27  air_ba937bf13d40fb24  2016-02-16        15     Tuesday        0   
28  air_ba937bf13d40fb24  2016-02-17        17   Wednesday        0   
29  air_ba937bf13d40fb24  2016-02-18        22    Thursday        0   

         genre                          area   latitude   longitude  \
0   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
1   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
2   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
3   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
4   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
5   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
6   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
7   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
8   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
9   Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
10  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
11  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
12  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
13  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
14  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
15  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
16  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
17  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
18  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
19  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
20  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
21  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
22  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
23  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
24  Dining bar  Tōkyō-to Minato-ku Shibakōen 

Some notes about this dataset: 
* hierarchical dataset 
* time series 

In [17]:
#pandas dataframes are actually numpy arrays underneath as seen below 
df.values

array([['air_ba937bf13d40fb24', '2016-01-13', 25, ..., 35.6580681,
        139.7515992, nan],
       ['air_ba937bf13d40fb24', '2016-01-14', 32, ..., 35.6580681,
        139.7515992, nan],
       ['air_ba937bf13d40fb24', '2016-01-15', 29, ..., 35.6580681,
        139.7515992, nan],
       ...,
       ['air_a17f0778617c76e2', '2017-03-26', 69, ..., 34.6951242,
        135.19785249999998, 35.0],
       ['air_a17f0778617c76e2', '2017-03-20', 31, ..., 34.6951242,
        135.19785249999998, 3.0],
       ['air_a17f0778617c76e2', '2017-04-09', 26, ..., 34.6951242,
        135.19785249999998, 32.0]], dtype=object)

In [18]:
df.median()

visitors             17.000000
holiday               0.000000
latitude             35.658068
longitude           139.670038
reserve_visitors     10.000000
dtype: float64

In [19]:
#can "chain" commands in OOP
df.tail(100).median()

visitors             75.000000
holiday               0.000000
latitude             35.661777
longitude           139.704051
reserve_visitors      7.000000
dtype: float64

In [23]:
#this is basically a Python dictionary lookup - key is column name and values are the contained values 
df['visitors']

0         25
1         32
2         29
3         22
4          6
          ..
252103    49
252104    60
252105    69
252106    31
252107    26
Name: visitors, Length: 252108, dtype: int64

for multiple columns, put them into a list 

In [24]:
df[['visitors','holiday','latitude']]

visitors  holiday   latitude
0             25        0  35.658068
1             32        0  35.658068
2             29        0  35.658068
3             22        0  35.658068
4              6        0  35.658068
...          ...      ...        ...
252103        49        0  34.695124
252104        60        0  34.695124
252105        69        0  34.695124
252106        31        1  34.695124
252107        26        0  34.695124

[252108 rows x 3 columns]

**looking things up by index uses the command iloc()**

In [27]:
#returns the first 10 rows and first 5 columns
df.iloc[:10, :5]

id  visit_date  visitors day_of_week  holiday
0  air_ba937bf13d40fb24  2016-01-13        25   Wednesday        0
1  air_ba937bf13d40fb24  2016-01-14        32    Thursday        0
2  air_ba937bf13d40fb24  2016-01-15        29      Friday        0
3  air_ba937bf13d40fb24  2016-01-16        22    Saturday        0
4  air_ba937bf13d40fb24  2016-01-18         6      Monday        0
5  air_ba937bf13d40fb24  2016-01-19         9     Tuesday        0
6  air_ba937bf13d40fb24  2016-01-20        31   Wednesday        0
7  air_ba937bf13d40fb24  2016-01-21        21    Thursday        0
8  air_ba937bf13d40fb24  2016-01-22        18      Friday        0
9  air_ba937bf13d40fb24  2016-01-23        26    Saturday        0

## Conditionals

In [28]:
#selecting just holidays 
#first generate the boolean index 
df['holiday'] > 0

0         False
1         False
2         False
3         False
4         False
          ...  
252103    False
252104    False
252105    False
252106     True
252107    False
Name: holiday, Length: 252108, dtype: bool

now you can just wrap that in the df index thingy to return all rows for which the boolean evaluates to TRUE 

In [31]:
df[df['holiday'] == 1]

id  visit_date  visitors day_of_week  holiday  \
23      air_ba937bf13d40fb24  2016-02-11         3    Thursday        1   
174     air_ba937bf13d40fb24  2016-08-11         2    Thursday        1   
176     air_ba937bf13d40fb24  2016-08-13        21    Saturday        1   
205     air_ba937bf13d40fb24  2016-09-22        21    Thursday        1   
241     air_ba937bf13d40fb24  2016-11-03        12    Thursday        1   
...                      ...         ...       ...         ...      ...   
251869  air_8e8f42f047537154  2017-03-20        32      Monday        1   
251935  air_bb4ff06cd661ee9b  2017-03-20        40      Monday        1   
251988  air_cf5ab75a0afb8af9  2017-03-20        63      Monday        1   
252039  air_1c0b150f9e696a5f  2017-03-20       136      Monday        1   
252106  air_a17f0778617c76e2  2017-03-20        31      Monday        1   

                               genre                                area  \
23                        Dining bar        Tōkyō-to Minato-ku Shibakōen   
174                       Dining bar        Tōkyō-to Minato-ku Shibakōen   
176                       Dining bar        Tōkyō-to Minato-ku Shibakōen   
205                       Dining bar        Tōkyō-to Minato-ku Shibakōen   
241                       Dining bar        Tōkyō-to Minato-ku Shibakōen   
...                              ...                                 ...   
251869                   Cafe/Sweets  Tōkyō-to Suginami-ku Asagayaminami   
251935                 Japanese food     Tōkyō-to Shinagawa-ku Hiromachi   
251988          Yakiniku/Korean food      Miyagi-ken Sendai-shi Kamisugi   
252039  Okonomiyaki/Monja/Teppanyaki         Tōkyō-to Shibuya-ku Shibuya   
252106                Italian/French        Hyōgo-ken Kōbe-shi Kumoidōri   

         latitude   longitude  reserve_visitors  
23      35.658068  139.751599               NaN  
174     35.658068  139.751599               NaN  
176     35.658068  139.751599               NaN  
205     35.658068  139.751599               NaN  
241     35.658068  139.751599              12.0  
...           ...         ...               ...  
251869  35.699566  139.636438               3.0  
251935  35.609226  139.730186               3.0  
251988  38.269076  140.870403               3.0  
252039  35.661777  139.704051               3.0  
252106  34.695124  135.197852               3.0  

[12775 rows x 10 columns]

### Multiple comparisons

AND is & and OR is | 

In [35]:
#holidays on Wednesdays
df[(df['holiday'] == 1) & (df['day_of_week'] == 'Wednesday')]

id  visit_date  visitors day_of_week  holiday  \
259     air_ba937bf13d40fb24  2016-11-23         8   Wednesday        1   
679     air_25e9888d30b386df  2016-05-04        15   Wednesday        1   
1348    air_64d4491ad8cdb1c6  2016-11-23         7   Wednesday        1   
1490    air_64d4491ad8cdb1c6  2016-05-04        12   Wednesday        1   
1712    air_ee3a01f0c71a769f  2016-11-23        30   Wednesday        1   
...                      ...         ...       ...         ...      ...   
250222  air_947eb2cae4f3e8f2  2016-11-23        22   Wednesday        1   
250409  air_8d61f49aa0373492  2016-11-23        48   Wednesday        1   
250595  air_90ed0a2f24755533  2016-11-23        57   Wednesday        1   
250765  air_0164b9927d20bcc3  2016-11-23         3   Wednesday        1   
251021  air_a257c9749d8d0ff6  2016-11-23        28   Wednesday        1   

                               genre                                     area  \
259                       Dining bar             Tōkyō-to Minato-ku Shibakōen   
679                          Izakaya     Tōkyō-to Shinagawa-ku Higashigotanda   
1348                      Dining bar             Tōkyō-to Minato-ku Shibakōen   
1490                      Dining bar             Tōkyō-to Minato-ku Shibakōen   
1712                     Cafe/Sweets  Shizuoka-ken Hamamatsu-shi Motoshirochō   
...                              ...                                      ...   
250222                       Izakaya    Fukuoka-ken Fukuoka-shi Hakata Ekimae   
250409  Okonomiyaki/Monja/Teppanyaki              Tōkyō-to Shibuya-ku Shibuya   
250595                       Izakaya               Tōkyō-to Bunkyō-ku Sendagi   
250765                Italian/French             Tōkyō-to Minato-ku Shibakōen   
251021                       Izakaya          Hokkaidō Asahikawa-shi 6 Jōdōri   

         latitude   longitude  reserve_visitors  
259     35.658068  139.751599               NaN  
679     35.626568  139.725858               NaN  
1348    35.658068  139.751599               NaN  
1490    35.658068  139.751599               NaN  
1712    34.710895  137.725940               NaN  
...           ...         ...               ...  
250222  33.591358  130.414878               NaN  
250409  35.661777  139.704051               NaN  
250595  35.726802  139.758138               NaN  
250765  35.658068  139.751599               NaN  
251021  43.770635  142.364819               NaN  

[906 rows x 10 columns]